# Generated by Django 3.2.8 on 2021-10-14 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_price_to_unit_price'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ("collection_no1")
        """, """
            DELETE FROM store_collection
            WHERE title="collection_no1"`
        """)
    ]
